short_name = "numdot"
name = "NumDot Library for tensor math and scientific computation"
major = 0
minor = 1
patch = 0
status = "dev"
module_config = ""
website = "https://github.com/Ivorforce/NumDot"
docs = "latest"
